apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: latest-image-notifier
  namespace: jq-example-image
spec:
  imageRepositoryRef:
    name: base-image-container-repo
    namespace: jq-example-image
  policy:
    semver:
      range: v0.0.x
