apiVersion: pipeline.jquad.rocks/v1alpha1
kind: PipelineTrigger
metadata:
  name: pipelinetrigger-for-image
  namespace: jq-example-namespace
spec:
  source: 
    kind: ImagePolicy
    name: latest-image-notifier
  pipeline: 
    name: build-and-push-microservice-on-base-image-update
    serviceAccountName: default
    maxHistory: 5
    maxFailedRetries: 3
    workspace:
      name: workspace
      size: 1Gi
      accessMode: ReadWriteOnce
    inputParams:
      - name: "repo-url"
        value: "https://github.com/jquad-group/microservice.git"
      - name: "branch-name"
        value: "main"
      - name: "imageLocation"
        value: "ghcr.io/jquad-group/microservice"