apiVersion: pipeline.jquad.rocks/v1alpha1
kind: PipelineTrigger
metadata:
  name: pipelinetrigger-for-image
  namespace: jq-example-namespace
spec:
  source: 
    kind: GitRepository
    name: microservice-code-repo
  pipeline: 
    name: build-and-push-myproject-on-image-update
    serviceAccountName: default
    maxHistory: 3
    retries: 2 # if the first pipeline fails, retry another 2 times
    workspace:
      name: workspace
      size: 1Gi
      accessMode: ReadWriteOnce
    inputParams:
      - name: "repo-url"
        value: "https://github.com/my-project.git"
      - name: "branch-name"
        value: "main"
      - name: "imageLocation"
        value: "docker.io/org/image"