apiVersion: pipeline.jquad.rocks/v1alpha1
kind: PipelineTrigger
metadata:
  name: pipelinetrigger-for-git-project
  namespace: jq-example-namespace
spec:
  source: 
    kind: GitRepository
    name: microservice-code-repo
  pipeline: 
    name: build-and-push-microservice-on-git-push
    serviceAccountName: default
    maxHistory: 3
    maxFailedRetries: 2 
    securityContext:
      runAsUser: 1001
      runAsGroup: 1001
      fsGroup: 1001
    workspace:
      name: workspace
      size: 1Gi
      accessMode: ReadWriteOnce
    inputParams:
      - name: "repo-url"
        value: "https://github.com/jquad-group/microservice.git"
      - name: "branch-name"
        value: $.branchName
      - name: "commitid"
        value: $.commitId
      - name: "imageLocation"
        value: "docker.io/org/image"