# permissions for end users to edit pipelinetriggers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: pipelinetrigger-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: migrated-project
    app.kubernetes.io/part-of: migrated-project
    app.kubernetes.io/managed-by: kustomize
  name: pipelinetrigger-editor-role
rules:
- apiGroups:
  - pipeline.jquad.rocks
  resources:
  - pipelinetriggers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - pipeline.jquad.rocks
  resources:
  - pipelinetriggers/status
  verbs:
  - get
