apiVersion: pipeline.jquad.rocks/v1alpha1
kind: PipelineTrigger
metadata:
  labels:
    app.kubernetes.io/name: pipelinetrigger
    app.kubernetes.io/instance: pipelinetrigger-sample
    app.kubernetes.io/part-of: migrated-project
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: migrated-project
  name: pipelinetrigger-sample
spec:
  # TODO(user): Add fields here
