apiVersion: pipeline.jquad.rocks/v1alpha1
kind: PipelineTrigger
metadata:
  name: pipelinetrigger-for-pr
  namespace: jq-example-pr
spec:
  source: 
    apiVersion: pipeline.jquad.rocks/v1alpha1
    kind: PullRequest
    name: pullrequest-github-sample
  pipelineRun:
    apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      generateName: build-and-push-microservice-on-pr-
      namespace: jq-example-pr
      labels:
        app: microservice
    spec:      
      params:
      - name: "repo-url"
        value: "https://github.com/jquad-group/microservice.git"
      - name: "branch-name"
        value: $.head.label
      - name: "commitid"
        value: "asdas312rlkvln234"
      - name: "imageLocation"
        value: "docker.io/org/image"  
      pipelineRef: 
        name: build-and-push-microservice-on-pr
      serviceAccountName: default
      podTemplate:
        securityContext:
          runAsUser: 1001
          runAsGroup: 1001
          fsGroup: 1001
      workspaces:
      - name: workspace
        volumeClaimTemplate:
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 16Mi
            volumeMode: Filesystem