apiVersion: v1
data:
  accessToken: TkRjeE5UZzVPVFl6TVRVeE9pdmt3VCtibXVscktmUmxTOWlTUUtZcEdPd00K
kind: Secret
metadata:
  name: bitbucket-secret
  namespace: jq-example-pr
type: Opaque
---
apiVersion: pipeline.jquad.rocks/v1alpha1
kind: PullRequest
metadata:
  name: pullrequest-bitbucket-sample
  namespace: jq-example-pr
spec:
  gitProvider:
    provider: Bitbucket
    secretRef: bitbucket-secret
    bitbucket:
      restEndpoint: https://bitbucket.jquad.rocks/rest
      project: jquad
      repository: microservice
  targetBranch: 
    name: refs/heads/main
  interval: 1m