apiVersion: v1
data:
  # admin
  password: YWRtaW4= 
  # admin
  username: YWRtaW4=
kind: Secret
metadata:
  name: bitbucket-secret
  namespace: jq-example-namespace
type: Opaque
---
apiVersion: pipeline.jquad.rocks/v1alpha1
kind: PullRequest
metadata:
  name: pullrequest-bitbucket-sample
  namespace: jq-example-namespace
spec:
  gitProvider:
    provider: Bitbucket
    secretRef: bitbucket-secret
    bitbucket:
      restEndpoint: https://bitbucket.jquad.rocks/rest
      project: jquad
      repository: microservice
  targetBranch: 
    name: refs/heads/main
  interval: 1m